### ISSUE TITLE
CS12 minor upgrades stop services but then don't start them

### ISSUE THREAD

**Issue by irvingpop** [chef/chef-server#72] opened 2015-01-28 00:04 UTC
Testing an upgrade today on an HA cluster, bootstrap backend going from 12.0.1 to 12.0.2:

```
chef-server-ctl upgrade
...
[2015-01-27T18:57:39-05:00] INFO: Chef Run complete in 24.796961175 seconds
[2015-01-27T18:57:39-05:00] INFO: Running report handlers
[2015-01-27T18:57:39-05:00] INFO: Report handlers complete
opscode Reconfigured!
ok: down: bookshelf: 0s
ok: down: nginx: 1s
ok: down: oc_bifrost: 0s
ok: down: oc_id: 1s
ok: down: opscode-chef-mover: 9999s, normally up
ok: down: opscode-erchef: 0s
ok: down: opscode-expander: 0s
ok: down: opscode-expander-reindexer: 0s
ok: down: opscode-solr4: 1s
ok: down: postgresql: 0s
ok: down: rabbitmq: 0s
ok: down: redis_lb: 1s
ok: run: postgresql: (pid 24724) 0s, normally down
[private-chef-upgrade] - Latest Migration Available: 1.19
[private-chef-upgrade] - Migrations to Run: []
Chef Server Upgraded!
```

examining the server post-upgrade:

```
root@ip-rh-backend1 data]# chef-server-ctl status
the ffi-yajl and yajl-ruby gems have incompatible C libyajl libs and should not be loaded in the same Ruby VM
falling back to ffi which might work (or might not, no promises)
down: bookshelf: 66s; run: log: (pid 16428) 10022s
run: keepalived: (pid 16579) 10018s; run: log: (pid 16597) 10017s
down: nginx: 66s; run: log: (pid 16556) 10018s
down: oc_bifrost: 65s; run: log: (pid 16114) 10027s
down: oc_id: 65s; run: log: (pid 16252) 10026s
down: opscode-erchef: 64s; run: log: (pid 16452) 10021s
down: opscode-expander: 64s; run: log: (pid 16430) 10022s
down: opscode-expander-reindexer: 63s; run: log: (pid 16373) 10023s
down: opscode-solr4: 62s; run: log: (pid 16310) 10025s
run: postgresql: (pid 24724) 59s, normally down; run: log: (pid 16034) 10028s
down: rabbitmq: 61s; run: log: (pid 15995) 10029s
down: redis_lb: 61s; run: log: (pid 16522) 10019s
```

**Comment by tylercloke** [comment] 2015-02-13 18:58
Don't the install instructions explicitly say to stop all services before doing the upgrade? The assumption is that things are down in general for all upgrades. If the docs don't say so, we should ask people to run `chef-server-ctl start` after upgrade, but this is not unexpected behavior afaik.

**Comment by irvingpop** [comment] 2015-02-13 19:25
Yeah, @stevendanna pointed out the doc change to me after I posted this.  What I'd like to understand is:  under what circumstance would our customers *want* their Chef server to be down after the upgrade is complete?

**Comment by sdelano** [comment] 2015-05-13 19:26
@irvingpop there's an interesting bit here that may help focus the discussion:

In the past, the upgrade (internally) did the following (after you'd stopped the Chef Server):

```
chef-server-ctl reconfigure # get all the services configured correctly
partybus upgrade
```

In the reconfigure, depending on the version bump and the different pieces that changed and have different config bits, the `chef-client` run in the reconfigure would bring services up and leave them there.

In the partybus upgrade, we still expected everything to be down, and sometimes we'd get burned by the fact that weird services were up or in a state that we didn't expect them to be.

With Chef Server 12, we're now very explicit about what we expect:

* everything is down at the start
* reconfigure runs
* we, again, stop everything
* partybus runs, and brings up only the services it needs for each migration, stopping them at the end

This has resulted in migrations (EC -> CS12 and CS12 -> CS12) that have been less painful than they were in the past.

It's interesting, in your description, that PostgreSQL is running after the upgrade. Like @tylercloke mentioned, everything should be stopped.

**Comment by sdelano** [comment] 2015-05-13 19:29
And I've detected the reason that PostgreSQL remains up: [link](https://github.com/chef/opscode-omnibus/blob/12.0.2/files/private-chef-ctl-commands/upgrade.rb#L103-L112)

**Comment by irvingpop** [comment] 2015-05-13 20:39
@sdelano I totally agree with the reasoning for partybus stopping all of the services and upgrades go way better than they used to be.

I was only questioning the end-state of leaving the services down.   If I'm in the minority in thinking that we should start the services after upgrade, just say so and I'll let it go :smiley:

**Comment by mmzyk** [comment] 2015-05-13 20:59
Pulling at my memories here, I think in the docs we tell you to stop the server before an upgrade, which stops all the services and the expectation is obviously that you'll start the services again after the upgrade. 

There was also the question of the state the services started in if someone doesn't stop them first - it's possible for someone to have certain services disable (bookshelf, for instance) but the upgrade process doesn't track the state of the services when the upgrade starts, so it can't know the state of the services that it should finish with. Therefore it's left up to the user to restore things to the state they should be. 

That's the reasoning it behaves the way it does if I remember correctly, although that doesn't mean that we couldn't improve the process (capture service state somehow and restore to that at the end of the upgrade? print out instructions on the need to restart the services? just start everything?).

**Comment by sean-horn** [comment] 2015-06-27 20:23
Noticed this with a major customer's upgrade. Any one of @mmzyk 's possible improvements works for me.

**Comment by PrajaktaPurohit** [comment] 2020-07-24 21:50
Closing this for now. https://docs.chef.io/install_server/  lists the process we follow for installs and upgrades. Please feel free to reopen in case of issues.

**Closed by PrajaktaPurohit** 2020-07-24 21:50 UTC
