### ISSUE TITLE
chef-backend-ctl create-cluster creates broken cluster if ipv6 is turned on

### ISSUE THREAD

**Issue by voroniys** [chef/chef-server#1111] opened 2017-03-03 12:07 UTC
chef-backend-1.3.2-1.el7.x86_64 on RHEL7
If ipv6 is enebled in the kernel 
chef-backend-ctl create-cluster 
produces broken cluster - leaderl is constantly failing with the following error message:
`2017-03-02_22:51:09.89234 Root: /opt/chef-backend/embedded/service/leaderl
2017-03-02_22:51:11.03097 {error_logger,{{2017,3,2},{23,51,11}},"Protocol: ~tp: register/listen error: ~tp~n",["inet_tcp",econnrefused]}
2017-03-02_22:51:11.03104 {error_logger,{{2017,3,2},{23,51,11}},crash_report,[[{initial_call,{net_kernel,init,['Argument__1']}},{pid,<0.473.0>},{registered_name,[]},{error_info,{exit,{error,badarg},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,344}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}},{ancestors,[net_sup,kernel_sup,<0.460.0>]},{messages,[]},{links,[#Port<0.1119>,<0.470.0>]},{dictionary,[{longnames,true}]},{trap_exit,true},{status,running},{heap_size,610},{stack_size,27},{reductions,821}],[]]}
2017-03-02_22:51:11.03140 {error_logger,{{2017,3,2},{23,51,11}},supervisor_report,[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{'EXIT',nodistribution}},{offender,[{pid,undefined},{id,net_kernel},{mfargs,{net_kernel,start_link,[['leaderl@127.0.0.1',longnames]]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
2017-03-02_22:51:11.03169 {error_logger,{{2017,3,2},{23,51,11}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}},{offender,[{pid,undefined},{id,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
2017-03-02_22:51:11.03253 {error_logger,{{2017,3,2},{23,51,11}},crash_report,[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.459.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,134}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}},{ancestors,[<0.458.0>]},{messages,[{'EXIT',<0.460.0>,normal}]},{links,[<0.458.0>,<0.457.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,376},{stack_size,27},{reductions,117}],[]]}
2017-03-02_22:51:11.03327 {error_logger,{{2017,3,2},{23,51,11}},std_info,[{application,kernel},{exited,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
2017-03-02_22:51:11.53456 {"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}}"}
`
Disabling ipv6 is solving the issue.

**Comment by voroniys** [comment] 2017-03-09 10:41
epmd is not running at all:

```
# chef-backend-ctl stop
ok: down: leaderl: 0s, normally up
ok: down: etcd: 1s, normally up
ok: down: postgresql: 0s, normally up
ok: down: elasticsearch: 0s, normally up
# chef-backend-ctl start
ok: run: leaderl: (pid 7710) 1s
ok: run: etcd: (pid 7753) 0s
ok: run: postgresql: (pid 7765) 1s
ok: run: elasticsearch: (pid 7773) 0s
# sudo netstat -lnp | grep epmd
#
```
BUT if I start it manually it just starts with no issues  and everything seems to be running correctly:
```
# /opt/chef-backend/embedded/lib/erlang/erts-7.3/bin/epmd -daemon
[root@clrv0000000086 ~]# /opt/chef-backend/embedded/lib/erlang/erts-7.3/bin/epmd -names
epmd: up and running on port 4369 with data:
name leaderl at port 34920

```
I've tried to look at /v2/keys/cb/ and before I've started epmd it was broken:
`{"action":"get","node":{"key":"/cb","dir":true,"nodes":[{"key":"/cb/control","dir":true,"modifiedIndex":5,"createdIndex":5}],"modifiedIndex":5,"createdIndex":5}}
`
but after manual start everything seems to be ok:
`{"action":"get","node":{"key":"/cb","dir":true,"nodes":[{"key":"/cb/status","dir":true,"modifiedIndex":12,"createdIndex":12},{"key":"/cb/control","dir":true,"modifiedIndex":5,"createdIndex":5},{"key":"/cb/leader","dir":true,"modifiedIndex":6,"createdIndex":6}],"modifiedIndex":5,"createdIndex":5}}`

**Comment by voroniys** [comment] 2017-03-09 11:26
I think I need to clarify issues with disabling ipv6 -in my configuration it is always disabled, but systems with issue has it disabled via sysctl. To solve the issue I was needed to disable it in grub and reboot the server.

**Comment by srenatus** [comment] 2017-03-09 20:00
@voroniys epmd isn't handled like any other service, it's started _"on demand"_ when an Erlang VM is started which requires it. (So it makes sense to not see it in `-ctl status` and not being able to control its state via any of the -ctl commands. It's pretty much handled "implicitly".)

Leaderl will be instructed to connect to epmd on 127.0.0.1, so it would be interesting to know which interfaces _your_ epmd instance ends up listening on when you start it manually -- with ipv6 enabled.

I can reproduce that same output when running something on that port (`127.0.0.1:4369`) that is not responding in the proper way (I've used `nc -k -l 127.0.0.1 4369`.) So, it seems when ipv6 is enabled on your machine, epmd would misbehave? Could your share the output of `/opt/chef-backend/embedded/service/leaderl/erts-7.3/bin/epmd -debug` when started with ipv6 enabled? (Could you also run `sudo netstat -lnp | grep 4369` to ensure nothing else is using that port? (It's a long shot, since when you manually start it, it comes up.) Another thing to try is `tcpdump -i any port 4369` when epmd is not running, while starting chef-backend.

(Also: please be aware that you're helping me satisfy my curiosity here, and while I'm giving my best to help you, this isn't the support channel for the "Chef server premium add-on" chef-backend. 😃 [Support starts here, I suppose.](https://www.chef.io/support/) That said, I find this very interesting, don't get me wrong.)

**Comment by srenatus** [comment] 2017-03-09 20:11
http://erlang.org/pipermail/erlang-questions/2016-March/088427.html This sounds promising, too. It's symptoms seem to come close to yours -- disabling IPv6 completely makes epmd start. Could you check what's stated there, please? 😃

**Comment by srenatus** [comment] 2017-03-10 07:36
I've played a bit more with the described settings in that mailing list post and the following scenario sounds most likely to me:

1. the loopback interface has no ipv6 address:
    ```
    root@api:~# ip addr show dev lo
    1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
        link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
        inet 127.0.0.1/8 scope host lo
           valid_lft forever preferred_lft forever
    ```
    Note the absence of any `inet6 ::1/128` line. This can be changed via `sysctl`:
    ```
    root@api:~# sysctl net.ipv6.conf.lo.disable_ipv6
    net.ipv6.conf.lo.disable_ipv6 = 1
    ```
2. starting `epmd` _with `ERL_EPMD_ADDRESS` set to anything_ makes it try to bind to `127.0.0.1` and `::1`, and the latter fails:
    ```
    root@api:~# ERL_EPMD_ADDRESS=127.0.0.1 /opt/chef-backend/embedded/service/leaderl/erts-7.3/bin/epmd -debug
    epmd: Fri Mar 10 08:26:48 2017: epmd running - daemon = 0
    epmd: Fri Mar 10 08:26:48 2017: failed to bind socket: Cannot assign requested address
    ```
3. starting `epmd` _without `ERL_EPMD_ADDRESS`_ just works, as it doesn't try to bind `::1`:
    ```
    root@api:~# /opt/chef-backend/embedded/service/leaderl/erts-7.3/bin/epmd -debug
    epmd: Fri Mar 10 08:29:45 2017: epmd running - daemon = 0
    ```

(3.) is what makes debugging this so surprising -- and (2.) is what makes epmd *not come up* when chef-backend's leaderl is started: its env will contain `ERL_EPMD_ADDRESS=127.0.0.1`.

Now, workarounds mentioned in the mailing list post:
> So either enable IPv6 for the loopback or disable IPv6 completely by passing `"ipv6.disable=1`" at boot.

Boot-time disabling is what you've found already. I could imagine that setting `sysctl net.ipv6.conf.lo.disable_ipv6=0` is a more convenient way?

(That said, we'll discuss this internally to see whether we really need the `ERL_EPMD_ADDRESS` setting in the first place.)

I'm curious to hear from you on this matter -- please disregard my "data gathering inquiries" from above, this now is much less stabbing in the dark than [this comment was](https://github.com/chef/chef-server/issues/1111#issuecomment-285464168). :smile:

**Comment by voroniys** [comment] 2017-03-10 08:20
Yes, this is exactly the case - enabling ipv6 on lo also solves the problem. 
The reason why I've posted this issue was not seeking for support - I managed to solve it by disabling ipv6 at the boot time. I don't need it anyway. But the idea was to improve the quality of Chef code itself.
You have perfectly pinpoint the real cause, so, I believe the issue can be solved.

**Comment by srenatus** [comment] 2017-03-10 09:13
🎉 I'm glad to hear this.

Thanks for bringing this up and engaging in debugging this with me. 😃 

I'll close this issue and try to get its learnings into the product. 😉

**Closed by srenatus** 2017-03-10 09:13 UTC

**Comment by eddesmet** [comment] 2017-03-15 02:50
Not sure if it is too late to comment on this thread but I have also found where /etc/hosts.deny is set to ALL; ALL you need to have a /etc/hosts.allow entry of ALL: ::1

**Comment by srenatus** [comment] 2017-03-15 08:20
@eddesmet It's never too late 😉 I'm not sure I follow, though -- is it that in some restricted setting (restricted via `hosts.deny`), `epmd` wouldn't come up? Or is it a related thing whose chain of causation might not be fully understood yet?
I'd like to understand this, especially since I'm not aware which the services in this setting _care_ for these files. I so far thought only inetd-managed stuff (and apparently sshd, according to [some documentation google swept up](http://its.virginia.edu/unixsys/sec/hosts.html)) would respect these files.

**Comment by stevendanna** [comment] 2017-03-15 08:45
It definitely looks like the root cause might be a bit more complicated. Even with the following set:

```
$ tail -1 /etc/hosts.deny
ALL: ALL
```

`epmd` is still able to bind to both ipv4 and ipv6 localhost: 

```
socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 3
setsockopt(3, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
bind(3, {sa_family=AF_INET, sin_port=htons(4369), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
listen(3, 128)                          = 0
socket(PF_INET6, SOCK_STREAM, IPPROTO_IP) = 4
setsockopt(4, SOL_IPV6, IPV6_V6ONLY, [1], 4) = 0
setsockopt(4, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
fcntl(4, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(4, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
bind(4, {sa_family=AF_INET6, sin6_port=htons(4369), inet_pton(AF_INET6, "::", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = 0
listen(4, 128)                          = 0
select(5, [3 4], NULL, NULL, {5, 0})    = 0 (Timeout)
```
