### ISSUE TITLE
About to choose an attribute as displayname when authenticating with LDAP

### ISSUE THREAD

**Issue by dongwon** [chef/chef-server#971] opened 2016-10-17 03:35 UTC
It seems not possible to choose an attribute as displayname when authenticating with LDAP, am I right?
It would be great if we can configure that on chef-server.rb because we sometimes see different use cases and formats of attributes on user schema so at that time we need to choose appropriate one depending on the situation. For me, the displayname is combined with english and korean name within a parenthesis, so it is too long and the Korean characters get always broken. And most importantly, I only have read permission for the LDAP access and the administrator of the LDAP service will not let me alter their format or schema.

**Comment by marcparadise** [comment] 2016-11-04 16:23
Closing as a duplicate of #800

**Closed by marcparadise** 2016-11-04 16:23 UTC
Labels: enhancement, ldap
