### ISSUE TITLE
Unable to reconfigure new chef-server install - postgres not accepting connections on 5432

### ISSUE THREAD

**Issue by davenorthcreek** [chef/chef-server#89] opened 2015-02-12 21:57 UTC
On Ubuntu 14.04 Server.
psql is looking for the socket at /var/run/postgresql/.s.PGSQL.5432

If I edit /var/opt/opscode/postgresql/9.2/data/postgresql.conf to change the unix_socket_directory
(a) it is rolled back during the reconfigure
(b) postgres is found by part of the reconfigure
(c) reconfigure then dies looking for /tmp/.s.PGSQL.5432

So which socket should I use?  Apparently /tmp.  But then why does having the socket in /tmp not work for part of the Reconfigure?

    ---- Begin output of bundle exec rake db:migrate ----
    STDOUT: 
    STDERR: rake aborted!
    PG::ConnectionBad: could not connect to server: Connection refused
    	Is the server running on host "127.0.0.1" and accepting
    	TCP/IP connections on port 5432?
    /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/activerecord-4.1.8/lib/active_record/connection_adapters/postgresql_adapter.rb:888:in `initialize'

**Comment by davenorthcreek** [comment] 2015-02-12 22:08
Tried the following:

    sudo ln -s /tmp/.s.PGSQL.5432 /var/run/postgresql/

Hoping that the socket would be the primary problem and this workaround would fix it.

Ran 

    sudo chef-server-ctl reconfigure

again and it died again.  Checked the postgres logs and found:

    2015-02-12_21:49:31.93866 LOG:  database system is ready to accept connections
    2015-02-12_21:49:31.94005 LOG:  autovacuum launcher started
    2015-02-12_22:02:42.37008 FATAL:  no pg_hba.conf entry for host "[local]", user "postgres", database "postgres", SSL off

log file:

    /var/log/opscode/postgresql/9.2/current

**Comment by stevendanna** [comment] 2015-02-13 09:17
@davenorthcreek Thanks for the report.  Do you mind providing the entire output of `chef-server-ctl reconfigure` as well as `chef-server-ctl status`?  My hunch is that the problem isn't with postgresql's configuration, but with the configuration for the oc_id (one of the chef-server services) database migration.  Could you also list any local environment variables before running those commands, using the `env` command?

**Comment by davenorthcreek** [comment] 2015-02-13 16:09
https://gist.github.com/davenorthcreek/ea8987f251d999fd8f86

**Comment by davenorthcreek** [comment] 2015-02-13 16:11
Output of env:

    XDG_SESSION_ID=1
    GEM_HOME=/home/dblock/.chefdk/gem/ruby/2.1.0
    TERM=xterm
    SHELL=/bin/bash
    SSH_CLIENT=192.168.1.124 45465 22
    OLDPWD=/var/opt/opscode
    SSH_TTY=/dev/pts/0
    ANT_HOME=/usr/share/ant
    USER=dblock  
    MAIL=/var/mail/dblock
    PATH=/opt/chefdk/bin:/home/dblock/.chefdk/gem/ruby/2.1.0/bin:/opt/chefdk/embedded/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/share/ant/bin
    PWD=/home/dblock
    JAVA_HOME=/usr/
    LANG=en_CA.UTF-8
    SHLVL=1
    HOME=/home/dblock
    LANGUAGE=en_CA:en
    GEM_ROOT=/opt/chefdk/embedded/lib/ruby/gems/2.1.0
    LOGNAME=dblock
    GEM_PATH=/home/dblock/.chefdk/gem/ruby/2.1.0:/opt/chefdk/embedded/lib/ruby/gems/2.1.0
    SSH_CONNECTION=192.168.1.124 45465 192.168.1.139 22
    XDG_RUNTIME_DIR=/run/user/1000
    _=/usr/bin/env

**Comment by stevendanna** [comment] 2015-02-25 01:36
Apologies for not following up here.  Is this still an issue for you?

**Comment by davenorthcreek** [comment] 2015-02-25 01:53
Yes, I'm still stuck.  If it doesn't get fixed I'll go in a different direction, but this is Chef's chance.

Thanks for not losing my ticket!

**Comment by stevendanna** [comment] 2015-02-25 08:49
@davenorthcreek You're best bet might be to reach out to support@chef.io.  I think I'm fairly time-zoneshifted from you and they will be able to respond more promptly.  However, let's see if we can't knock this out quickly.  I think I failed to read your original message closely enough.

In your original message you mentioned: 

> psql is looking for the socket at /var/run/postgresql/.s.PGSQL.5432

Were you trying to use psql from a distribution provided package?  The one shipped in the chef-server package should look at /tmp:

```
root@vagrant:~# su - opscode-pgsql
$ bash
opscode-pgsql@vagrant:~$ strace /opt/opscode/embedded/bin/psql 2>&1 | grep /tmp
connect(3, {sa_family=AF_FILE, path="/tmp/.s.PGSQL.5432"}, 110) = 0
```

If this was the only problem before your initial attempt to reconfigure the unix socket location, I would suggest using the built-in psql binary rather than the distribution provided one.

Note that you usually shouldn't have to touch psql directly if all goes well.  If your server is in a non-working state because of previous attempts to fix this issue, I would try the install from almost scratch:

chef-server-ctl cleanse
chef-server-ctl reconfigure

## some more background

In an out-of-the-box install, the socket should end up in /tmp already without any reconfiguration:

```
vagrant@vagrant:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.4 LTS
Release:        12.04
Codename:       precise
vagrant@vagrant:~$ ls -al /tmp/.s.PGSQL.5432
srwxrwxrwx 1 opscode-pgsql opscode-pgsql 0 Feb 25 08:14 /tmp/.s.PGSQL.5432
```

The oc_id migration uses the tcp socket rather then the unix socket:

```
sudo -E strace bundle exec rake db:migrate 2>&1 | grep 5432
connect(7, {sa_family=AF_INET, sin_port=htons(5432), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (Operation now in progress)
```

If this migration fails even on a clean installation, check the postgres logs (as you did before) and double check the postgresql is listening on TCP port 5432.

**Comment by davenorthcreek** [comment] 2015-02-25 22:22
Hi!  Thanks!

You know how something twigs?

I was doing some testing of a facebook login snippet and had commented
out localhost 127.0.0.1 in /etc/hosts.

Uncomment.

Cleanse.
Reconfigure.

Everything works!

Have a great day down there!  Enjoy summer!

-Dave
northcreek.ca
@northcreeksoft
Buried in winter :-)

**Comment by stevendanna** [comment] 2015-02-25 23:03
Glad to hear this got sorted.  Closing this ticket out.  Thanks!

**Closed by stevendanna** 2015-02-25 23:03 UTC

**Comment by arunachalaramana** [comment] 2016-06-24 16:32
Having a similar problem! host is intact! getting the following error on
sudo chef-compliance-ctl cleanse
sudo chef-comliance-ctl reconfigure
reconfiguration ends up with error
even completer purge and dpkg installation followed by reconfigure ends up with the same error
Running handlers:
[2016-06-24T20:56:24+05:30] ERROR: Running exception handlers
Running handlers complete
[2016-06-24T20:56:24+05:30] ERROR: Exception handlers complete
Chef Client failed. 23 resources updated in 01 minutes 37 seconds
[2016-06-24T20:56:24+05:30] FATAL: Stacktrace dumped to /opt/chef-compliance/embedded/cookbooks/cache/chef-stacktrace.out
[2016-06-24T20:56:24+05:30] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-06-24T20:56:24+05:30] FATAL: Mixlib::ShellOut::ShellCommandFailed: enterprise_pg_database[chef_compliance] (chef-compliance::_postgresql-enable line 47) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[create_database_chef_compliance] (/opt/chef-compliance/embedded/cookbooks/cache/cookbooks/enterprise/providers/pg_database.rb line 19) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of createdb --template template0 --encoding UTF-8 chef_compliance ----
STDOUT: 
STDERR: createdb: could not connect to database template1: FATAL:  no pg_hba.conf entry for host "[local]", user "chef-pgsql", database "template1", SSL off
---- End output of createdb --template template0 --encoding UTF-8 chef_compliance ----
Ran createdb --template template0 --encoding UTF-8 chef_compliance returned 1

**Comment by marcparadise** [comment] 2016-06-24 17:42
@arunachalaramana this appears to be a Chef Compliance install.  Please contact support@chef.io for further assistance.
