### ISSUE TITLE
DELETE /policy_groups/x/policies/y can leave an empty group

### ISSUE THREAD

**Issue by jkeiser** [chef/chef-server#654] opened 2015-12-04 23:28 UTC
I'm not sure if this is right or not, but when you delete the last policy in a group, the group remains and the list of policies is empty. There is no way to create a policy group, but it might be OK since you could DELETE /policy_groups/x if you wanted to.  cookbooks cleans up the cookbook when the last version is deleted; we probably should be doing that here as well.

Same thing with deleting the last revision of a policy.

**Comment by stevendanna** [comment] 2015-12-05 21:20
cc @danielsdeleo

**Comment by danielsdeleo** [comment] 2015-12-05 21:42
This is on purpose, I think there are pedant tests explicitly for this. My reasoning is that policy groups have ACLs which would "disappear" if you deleted the last one and then added a new one after.

There is also the proposed promotion API which would give policy groups actual data beyond just having a name. TBH, everyone likes it in the abstract but no one has said they actually need it, so who knows if/when that would be implemented. But if such a thing did exist, you wouldn't want to delete a policy group just because it was emptied, you'd lose the "promotion policy" data. (cf. https://github.com/chef/chef-rfc/blob/master/rfc042-policyfile-endpoint.md#promotion-api-optional )

**Comment by stevendanna** [comment] 2016-11-05 17:51
Based on @danielsdeleo response, I'm closing this since it appears to be working as intended.

**Closed by stevendanna** 2016-11-05 17:51 UTC
