### ISSUE TITLE
oc-id login screens look weird in Chef Server 12.1.0-rc.1

### ISSUE THREAD

**Issue by irvingpop** [chef/chef-server#325] opened 2015-06-02 22:40 UTC
The oc-id login screen appears different in 12.1.0-rc.1 and has a broken image at the top,  this may confuse or scare our users

![screen shot 2015-06-02 at 2 43 31 pm](https://cloud.githubusercontent.com/assets/1616328/7948931/8d0a168e-093d-11e5-84b4-d1f23a2ef902.png)

![screen shot 2015-06-02 at 2 43 48 pm](https://cloud.githubusercontent.com/assets/1616328/7948933/91531e2a-093d-11e5-9453-a9202ce0df77.png)

**Comment by irvingpop** [comment] 2015-06-02 22:56
ping: @chef/chef-visual-interaction

**Comment by smith** [comment] 2015-06-03 15:58
The changes to the look are by design and are part of overall efforts to improve the look and feel of all Chef applications. They are not going away and will continue to change and improve.

For that broken image, do you see any 404 messages in your browser console? It looks like it's failing to load the logo image. Please open a separate issue for that (though I believe it's probably fixed in #319.)

**Comment by irvingpop** [comment] 2015-06-03 16:52
@smith I'm reopening this issue per our discussion.   To close this issue I'd have the following criteria:

1.  #319 gets merged and validated in an omnibus build
2.  Release notes and Changelog get updated with a very prominent note about the visual change to the login screen

**Comment by stevendanna** [comment] 2015-06-06 09:52
I think that at the very least the broken images should be a 12.1 blocker.  The release notes are easy to update and I agree we should make note to any visual changes to the login screen.

**Comment by mmzyk** [comment] 2015-06-15 22:16
Do we consider this addressed? For @irvingpop's #1 concern, #319 was merged, and I believe #344 addressed @irvingpop's  #2 concern. I would close this, but having been out, I'm unsure if we consider this addressed.

**Comment by irvingpop** [comment] 2015-06-15 22:34
hey @mmzyk thanks for the update.  do you know if rc3 would reflect the changes?   If so, I can take it for a spin and validate.

**Comment by mmzyk** [comment] 2015-06-16 14:20
@irvingpop Yes, if this was fixed RC3 would reflect the changes.

**Comment by mmzyk** [comment] 2015-06-16 16:02
I loaded RC3 and brought up the oc-id signin page and it looks fine, so I'm closing this out. @irvingpop feel free to double check behind me.

**Closed by mmzyk** 2015-06-16 16:02 UTC
Labels: oc-id

**Comment by irvingpop** [comment] 2015-06-16 16:16
Hey @mmzyk confirming this resolved. One thing I did find: on the oc-id signin page, the "SIGN UP" link takes you to https://manage.chef.io/signup rather than the local server.

**Comment by mmzyk** [comment] 2015-06-23 04:26
@irvingpop Yeah, that's a regression from being too over eager in applying chef-web-core conventions. I've created https://github.com/chef/chef-server/issues/363 as an issue to get this fixed.
