### ISSUE TITLE
Error in  chef-server-ctl reconfigure 

### ISSUE THREAD

**Issue by marcparadise** [chef/chef-server#942] opened 2016-09-23 15:06 UTC
We've seen several reports now of `chef-server-ctl reconfigure` failing on its first run.  We have not been able to recreate this yet, though we're still looking into it. 

If you've encountered this, or encountered a failure with the same error (below) on subsequent reconfigures, please add a comment with the following:
- OS & version
- version of chef-server
- was this a clean install of chef-server or an upgrade? 
- any chef-server addon installed? 
- is chef-dk installed? If so, which version?
- have you installed any gems, either directly or via `chef_gem`? 

The error looks as follows: 

```
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:479:in remove_old_node_state: undefined method success? for nil:NilClass (NoMethodError)

from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:495:in <code style="background-color:#f1f1ff;padding:2px 5px">run_chef</code>



from /opt/opscode/embedded/service/omnibus-ctl/chef-server-ctl:222:in <code style="background-color:#f1f1ff;padding:2px 5px">reconfigure</code>



from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:736:in <code style="background-color:#f1f1ff;padding:2px 5px">run</code>



from /opt/opscode/embedded/service/omnibus-ctl/chef-server-ctl:237:in <code style="background-color:#f1f1ff;padding:2px 5px">&lt;main&gt;</code></p>

```

**Comment by marcparadise** [comment] 2016-09-23 15:20
The error is being reported from here: 

https://github.com/chef/omnibus-ctl/blob/master/lib/omnibus-ctl.rb#L479

The call that it's making to `run_command` uses `system` to execute the command. After running system, `$?` should always be a valid `Process::Status` but in this case is not.

**Comment by Tommyf** [comment] 2016-09-28 18:19
I just had a first-run fail on 'chef-server-ctl reconfigure'. The output is over 4000 lines long. Would you like it posted into here or provided a different way?

**Comment by marcparadise** [comment] 2016-09-28 20:05
If it failed in the same way (`undefined method success?`) the last lines before the start of the stack trace and the first few lines of stack trace will be enough.  Could you also include os , os version, chef server version, and amount of ram provisioned  (as reported by free -h) ?

If it's a different error , please open a separate issue - with the same subset of log

**Comment by marcparadise** [comment] 2016-09-28 20:06
Sorry, I missed that you included the Os/version info - just the ram needed

**Comment by ketank-new** [comment] 2016-12-27 09:57
version chef-12.12.4 rpm works fine on x86
Do let me know if this helps

**Comment by kadamvandita** [comment] 2017-01-10 13:21
Hi,

 The cause for chef-server-ctl reconfigure  failing on its first run could be as follows:
-The parameter node_cache_path  (https://github.com/chef/omnibus-ctl/blob/master/lib/omnibus-ctl.rb#L479) msut be getting set after the first run.
-In the first run as it is not set it must be returning null value causing chef-server-ctl reconfigure  to fail .
-In the second run as the value of node_cache_path  is set it must be executing chef-server-ctl reconfigure  .

**Comment by kbhute-ibm** [comment] 2017-02-01 09:24
+1

**Comment by marcparadise** [comment] 2017-02-01 18:33
Hi @kadamvandita , thanks for posting your thoughts here. 

We did look at that but what we're seeing here is that the `status` object [returned by run_command](https://github.com/chef/omnibus-ctl/blob/master/lib/omnibus-ctl.rb#L234) is `nil`. 

The normal behavior of using the $? status variable in this way is to return a `Process::Status` as you can see in this example:
```
irb(main):001:0> system("alsdkfjsaf")
=> nil
irb(main):002:0> puts $?
pid 24356 exit 127
=> nil
irb(main):003:0> puts $?.class
Process::Status

irb(main):020:0* puts $?.exitstatus
127

```
The nil `$?` is leading to the error you see on reconfigure, but we have not yet been able to track down any conditions in which a single process on a healthy system can have `$?` replaced with nil immediately after a `system` call.

Because there have been relatively few reports since this issue was opened and we have no scenario for reproducing it, it is currently further down our priority list.

**Comment by PrajaktaPurohit** [comment] 2019-12-18 21:33
@marcparadise Thank you for tracking and chasing this issue. It does not seem to have appeared for more than 2 years or with newer versions of chef. Closing this for now.

**Closed by PrajaktaPurohit** 2019-12-18 21:33 UTC
Labels: Status: Good First Issue
