### ISSUE TITLE
Rabbitmq SASL Log Grows Without Bounds

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#242] opened 2015-05-09 03:14 UTC
Zendesk 4194

As a customer, I would like Rabbitmq to clean up after itself, or be cleaned up.

The logfile `/var/opt/opscode/rabbitmq/log/rabbit@localhost-sasl.log` seems to grow without bounds, even in Chef Server 12.0.8

**Comment by stevendanna** [comment] 2016-11-06 16:45
@sean-horn Closing this as a duplicate of https://github.com/chef/chef-server/issues/603 even though this one came first.  There is a bit more discussion on that ticket.

**Closed by stevendanna** 2016-11-06 16:45 UTC
Labels: bug
