### ISSUE TITLE
Status endpoint fails due to RabbitMQ

### ISSUE THREAD

**Issue by zepheiryan** [chef/chef-server#1418] opened 2017-10-31 02:19 UTC
## Expected Behavior

Checking the `/_status` URL on a Chef Server should return HTTP 200 and 'pong' for all services listed there.

## Current Behavior

Returns HTTP 500 with `chef_index":"fail"` in the upstreams list.  This appears to be reflected in `/var/opt/opscode/rabbitmq/log/rabbitmq@localhost-sasl.log`:

```
=CRASH REPORT==== 31-Oct-2017::01:47:22 ===
  crasher:
    initial call: mochiweb_acceptor:init/4
    pid: <0.12853.0>
    registered_name: []
    exception exit: {error,accept_failed}
      in function  mochiweb_acceptor:init/4 (src/mochiweb_acceptor.erl, line 73)
    ancestors: [rabbit_web_dispatch_sup_15672,rabbit_web_dispatch_sup,
                  <0.10599.0>]
    messages: []
    links: [<0.10606.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 1145
  neighbours:
```

There is nothing besides a startup message in `/var/log/opscode/rabbitmq/current`.  Also, an indirect vote for #603 as we have a monitoring process that checks this URL periodically and it's going to cause that file to keep growing without log rotation configured.

## Steps to Reproduce (for bugs)

1. Access `http://chef-server/_status`

## Your Environment

* Chef Server Version: 12.17.5-1
* Total/free RAM and disk space: 8G total / 1G free RAM; 40G total / 34G free disk
* Operating System and Version: Ubuntu 16.04.3 LTS
* If upgrading, previous Chef Server version: 12.14.0
* Running in a container? No

Everything else appears to be working fine - Chef client runs on nodes, knife queries, knife from file updates, push jobs, etc., though I'm sure I haven't exercised all paths yet.  This seems to be related to the RabbitMQ management plugin not working properly in our install.

The server was newly created and the latest package installed today.  Data was migrated from its predecessor server without issue.  It serves no other main purpose and differs largely in operating system and Chef Server version from the predecessor.

**Comment by stevendanna** [comment] 2017-10-31 12:00
Thanks for the report.  That check is rather new (cc @jaym).  Do you get a different result if you try the same check manually with something like:

```
curl -k -u rabbitmgmt:$(chef-server-ctl show-secret rabbitmq management_password) https://127.0.0.1:15672/api/aliveness-test/%2Fchef
```

 Is rabbitmq working correctly via AMPQ:

```
PATH=/opt/opscode/embedded/bin:$PATH /opt/opscode/embedded/bin/rabbitmq-plugins list
PATH=/opt/opscode/embedded/bin:$PATH /opt/opscode/embedded/bin/rabbitmqctl node_health_check
PATH=/opt/opscode/embedded/bin:$PATH /opt/opscode/embedded/bin/rabbitmqctl list_vhosts
PATH=/opt/opscode/embedded/bin:$PATH /opt/opscode/embedded/bin/rabbitmqctl list_queues -p /chef | tail
```
In the erchef log (`/var/log/opscode/opscode-erchef/current`), are there any lines that start with:

```
Error getting Rabbitmq aliveness
```

From the sasl logs it appears rabbitmq wasn't able to accept() the new connection.  Does the condition persist across a restart of rabbitmq?  Are there any other processes trying to use port 15672?

**Comment by jaym** [comment] 2017-10-31 12:47
If the management plugin is not functioning correctly, the default configuration will think things are broken. You should be able to have any checks against rabbitmq disabled by disabling rabbitmq management:
```
rabbitmq['management_enabled'] = false
```

**Comment by zepheiryan** [comment] 2017-11-01 00:25
```
% curl ...
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.
```

The other commands look fine, and yes, that log file is getting full of that Rabbitmq aliveness message.

I took a look at `/var/opt/opscode/rabbitmq/etc/rabbitmq.config`, which it turns out uses our domain-specific certificate and key supplied for Chef Server `nginx[ssl_*]` settings.  I guess that error is to be expected, then - the management API is bound to and accessed via 127.0.0.1, but the cert it's supplying for HTTPS is for an actual domain.

Our `/var/opt/opscode` was copied over and dropped in place before running `chef-server-ctl upgrade` and a reconfigure for good measure.  I'm not sure how it picked up that setting, though maybe it's more globally applied than Nginx?  I don't think I saw any chef-server.rb options that would pass through more useful settings to RabbitMQ, nor did there seem to be any more obviously applicable certs around in `/var/opt/opscode`.

I'll gladly take disabling those specific checks as a useful fix for now.

**Comment by stevendanna** [comment] 2017-11-01 09:42
> I took a look at /var/opt/opscode/rabbitmq/etc/rabbitmq.config, which it turns out uses our domain-specific certificate and key supplied for Chef Server nginx[ssl_*] settings. I guess that error is to be expected, then - the management API is bound to and accessed via 127.0.0.1, but the cert it's supplying for HTTPS is for an actual domain.

Thanks for digging into this.  We do indeed re-use the nginx ssl config when setting up rabbitmq:

https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/private-chef/recipes/rabbitmq.rb#L82-L83

**Comment by jaym** [comment] 2017-11-01 13:01
IIRC, we had a similar issue that was caused by the rabbitmq user not being able to access the certificate

**Comment by jaym** [comment] 2017-11-01 14:07
There are 2 log files in `/var/opt/opscode/rabbitmq/log` that might have useful information in them. Please post anything you see in there that seems strange

**Comment by zepheiryan** [comment] 2017-11-02 22:16
Definitely should have looked in there earlier:

```
=ERROR REPORT==== 2-Nov-2017::22:04:24 ===
    application: mochiweb
    "Accept failed error"
    "{error,{options,{keyfile,\"/path/to/key\",\n                         {error,eacces}}}}"
```

It looks like the rabbitmq process user and group ID are both `opscode`, so adding the `opscode` user to the group that does have access to the key file for this reason doesn't help.  There are obvious quick fixes we could make around permissions, ownership, and/or file location, but that doesn't seem like a great way to keep this issue from popping up.  Perhaps the management interface should get its own cert setup unless otherwise configured?  I haven't paid attention to what happens when the user doesn't configure their own Nginx SSL certs, so not sure how much of an added burden that would be.

**Comment by stuszynski** [comment] 2017-11-29 15:30
We ran into the same issue. Is it safe to disable `rabbitmq_management` plugin in chef-server.rb? It looks like this mitigate the issue. However, I'm not sure if this will not break something else.

**Comment by jaym** [comment] 2017-11-29 17:22
I imagine nothing else will break. I believe this was broken before, and there was an update that checks to see if that endpoint says its healthy as part of the status check. There are places where the management endpoint is used, but they all check if its enabled since its optional

**Comment by bplessis** [comment] 2019-07-02 13:41
Look like disabling the management interface also remove the "oc_chef_action" component:

Before:
```
{
  "status": "fail",
  "upstreams": {
    "chef_solr": "pong",
    "chef_sql": "pong",
    "chef_index": "fail",
    "oc_chef_action": "fail",
    "oc_chef_authz": "pong"
  },
  ....
}
```

After:
```
{
  "status": "pong",
  "upstreams": {
    "chef_solr": "pong",
    "chef_sql": "pong",
    "chef_index": "pong",
    "oc_chef_authz": "pong"
  },
  ....
}
```

Is it of consequences ?

**Comment by PrajaktaPurohit** [comment] 2019-10-25 18:52
Next actions:
1. Check to see if this exists with the latest version of Chef Infra Server
2. Check if getting rid of the actions rabbitmq queue helps mitigate this.

**Comment by PrajaktaPurohit** [comment] 2020-12-22 03:20
Chef-Server 14 does not support Rabbitmq. Please let us know if upgrading to this version help with the mitigation.  Closing this for now. Feel free to reopen if needed.

**Closed by PrajaktaPurohit** 2020-12-22 03:20 UTC
Labels: Aspect: Correctness, Component: opscode-erchef, Status: Consider for next release, Triage: Try Reproducing, Type: Bug
