### ISSUE TITLE
Chef 12 'chef-server-ctl upgrade' fails on RHEL 5.11

### ISSUE THREAD

**Issue by btm** [chef/chef-server#127] opened 2015-03-13 20:06 UTC
Originally filed by @ve7cxz as https://github.com/chef/chef/issues/3072

====
I'm migrating from Chef 11 (11.1.3) to Chef 12 (12.0.5) on a RHEL 5.11 server, and running into an issue after running `chef-server-ctl upgrade`:-

    - configure service runit_service[rabbitmq]
    * link[/opt/opscode/service/rabbitmq] action create
      - create symlink at /opt/opscode/service/rabbitmq to /opt/opscode/sv/rabbitmq

At this point, it hangs. Running strace against the chef-client process shows it trying to stat `/opt/opscode/service/rabbitmq/supervise/ok`, which apparently doesn't exist:-

    stat("/opt/opscode/service/rabbitmq/supervise/ok", 0x7fffa031f450) = -1 ENOENT (No such file or directory)

I'm assuming this part of the `chef-server-ctl upgrade` is supposed to create it, but for some reason it isn't. I've attempted the upgrade twice now, and both times it has failed at the same point.

Exiting out of the upgrade leaves Chef 12 in a bad state, and it appears to then be impossible to continue the upgrade:-

    <...>
    Creating /tmp/chef11-server-data20150312-21492-nblrd0 as the location to save the open source Chef 11 server data
    Ensuring Chef 12 server is stopped
    warning: rabbitmq: unable to open supervise/ok: file does not exist
    Unable to stop the Chef 12 server, which is needed to complete the upgrade

The only way to get the upgrade process to work again is to uninstall the chef-server-core RPM and start again.

**Comment by ve7cxz** [comment] 2015-03-14 00:41
I actually managed to get this installed by starting `/opt/opscode/embedded/bin/runsvdir-start` from another terminal while `chef-server-ctl upgrade` is running. I'm still not sure why this doesn't happen automatically, though.

**Comment by mmzyk** [comment] 2015-03-14 05:14
@ve7cxz I'll try to look into this when I get a chance. Glad you got it working. I wanted to note that the references to private-chef-ctl are okay (you brought this up in the original issue before it was moved here). That is because the enterprise server and open source server merged and now there is only one server and it is completely open source. This new code though is based off the enterprise code base (although the old enterprise and open source code bases did share a lot of code). So the private-chef-ctl is just a naming reference that hasn't been cleaned up. chef-server-ctl and private-chef-ctl both run the same code under the hood - one is just a symlink to the other for now to ensure backwards compatibility.

**Comment by ve7cxz** [comment] 2015-03-14 10:31
@mmzyk cheers! I assumed the references were benign but I wanted to mention it just in case. It's an odd one because it looks like the `runsvdir-start` command gets added to `/etc/inittab`, but doesn't get started, which makes me wonder if the init reload to reread it never happens.

**Comment by stevendanna** [comment] 2015-06-17 16:43
I'm going to close this for now.  We haven't been able to reproduce this in upgrade testing.  If someone sees a reproduction case of this issue we can happily reopen it.

**Closed by stevendanna** 2015-06-17 16:43 UTC

**Comment by heaven** [comment] 2016-07-11 14:18
I see this on ubuntu, I tried to upgrade but there were broken cookbooks so I remove (apt-get autoremove) the chef-server-core package and killed runsv processes.

Now when I am trying to upgrade I see the next:
```
dpkg -i chef-server-core_12.8.0-1_amd64.deb
(Reading database ... 132335 files and directories currently installed.)
Preparing to replace chef-server-core 12.8.0-1 (using chef-server-core_12.8.0-1_amd64.deb) ...
Unpacking replacement chef-server-core ...
Setting up chef-server-core (12.8.0-1) ...
```

But nothing started. Then I start upgrade and it raises this exactly error. It seems I need to cleanup somewhere, but I have no Idea where, the installed doesn't suggest anything.

P.S. Upgrade process is terrible, it raises errors on each cookbook, you have to fix it and go through the entire process again and again. Spent the whole day and ended up with this error.
