### ISSUE TITLE
400 Bad Request trying to grant permissions to client when user has same name

### ISSUE THREAD

**Issue by jkeiser** [chef/chef-server#111] opened 2015-02-25 00:58 UTC
When a user on the server (but not in an org) has the same name as a client in the org, you cannot add that client to the permissions of any object.  It gives you back a 400 instead.  I would expect it to add the permissions (assuming the user isn't also in the org and there is no ambiguity).

This affects chef-provisioning and any client (including the webui) that tries to add permissions to objects.

Detail
------

When I have:
- An organization "foo" with node "bar"
- A user "mario" on the Hosted or Enterprise Chef Server who is not in organization "foo"
- A client "mario" in organization "foo"

And I do a `PUT /organizations/foo/nodes/bar` with:

```json
{
  "read": {
    "actors": [
      "mario",
      "pivotal"
    ]
  }
}
```

I expect the request to succeed and `mario` to have `read` access to `bar`.

Instead, I get this:

```
[2015-02-24T11:38:58-08:00] DEBUG: ---- HTTP Status and Header Data: ----
[2015-02-24T11:38:58-08:00] DEBUG: HTTP 1.1 400 Bad Request
[2015-02-24T11:38:58-08:00] DEBUG: server: ngx_openresty
[2015-02-24T11:38:58-08:00] DEBUG: date: Tue, 24 Feb 2015 19:38:57 GMT
[2015-02-24T11:38:58-08:00] DEBUG: content-type: text/html
[2015-02-24T11:38:58-08:00] DEBUG: content-length: 156
[2015-02-24T11:38:58-08:00] DEBUG: connection: close
[2015-02-24T11:38:58-08:00] DEBUG: x-ops-api-info: flavor=hec;version=12.0.0;oc_erchef=0.29.2
[2015-02-24T11:38:58-08:00] DEBUG: ---- End HTTP Status/Header Data ----
[2015-02-24T11:38:58-08:00] DEBUG: ---- HTTP Response Body ----
[2015-02-24T11:38:58-08:00] DEBUG: <html><head><title>400 Bad Request</title></head><body><h1>Bad Request</h1>Bad Request<p><hr><address>mochiweb+webmachine web server</address></body></html>
[2015-02-24T11:38:58-08:00] DEBUG: ---- End HTTP Response Body -----
```

**Comment by marcparadise** [comment] 2015-02-25 01:59
If you pull in the latest oc_erchef with multi-key (1.2.1 or later iirc) the long-standing set of "same name" bugs should be resolved.  Though I've not seen this particular one yet (400 isn't what I'd expect). I'll take a look tomorrow ‎to see if it's via unrelated path.  We're still working out the schedule for when this gets deployed to Hosted. It's in CS12 v12.0.3 and later, once I can confirm it fixed. Otherwise we'll add it to the list.

**Comment by stevendanna** [comment] 2015-02-25 07:57
@marcparadise I'm pretty sure this one is not covered by the keys work.  The actor in question here isn't the one making the request so the disambiguation strategy of the key work (figuring out the actor by looking at what key auth'd) doesn't apply.

**Comment by sdelano** [comment] 2015-05-13 21:24
@jkeiser - Did you try to PUT to the `/nodes/foo` endpoint with data that was intended for `/nodes/foo/_acl`? From the debug output provided, it's hard to tell. It would also be beneficial to get the debug output that includes the headers and any other information sent to the client, just in case this 400 was due to other such missing information.

**Comment by sdelano** [comment] 2015-05-13 23:51
Okay, I did some more digging here today, and regardless of the URLs put above, the premise is still true - you get a `400 Bad Request` back from the API when you try to add a client with the same name as another user on the Chef Server that's not in the current org. You do not, however, get a 400 when you try to add a client that does not have a matching username.

Testing this out locally, I get the following log message from `oc_erchef`:

```
2015-05-13T21:40:54Z erchef@127.0.0.1 method=PUT; path=/organizations/stephen-org/nodes/bar/_acl/update; status=400; req_id=g3IAA2QAEGVyY2hlZkAxMjcuMC4wLjEDAAIlYwAAAAAAAAAA; org_name
=stephen-org; msg=bad_actor; couchdb_groups=false; couchdb_organizations=false; couchdb_containers=false; couchdb_acls=false; 503_mode=false; couchdb_associations=false; couchdb_association_requests=false; req_time=23; rdbms_time=5; rdbms_count=4; user=stephen; req_api_version=0; 
```

**Comment by sdelano** [comment] 2015-05-14 00:15
And I've located the code that has an obvious bug in it [here](https://github.com/chef/chef-server/blob/master/src/oc_erchef/apps/oc_chef_authz/src/oc_chef_authz_acl.erl#L173-L177):

```erlang
convert_actor_names_to_ids(Names, OrgId) ->
    ClientIds = oc_chef_group:find_client_authz_ids(Names, OrgId,
                                                    fun chef_sql:select_rows/1),
    UserIds = oc_chef_group:find_user_authz_ids(Names, fun chef_sql:select_rows/1),
    ClientIds ++ UserIds.

names_to_ids(Ace, OrgId) ->
    ActorNames = ej:get({<<"actors">>}, Ace),
    GroupNames = ej:get({<<"groups">>}, Ace),
    ActorIds = convert_actor_names_to_ids(ActorNames, OrgId),
    % Check to make sure everything got converted; if something is missing,
    % there was an invalid actor or group name in the request body
    case length(ActorNames) == length(ActorIds) of
        false ->
            throw(bad_actor);
        _ ->
            %% the rest doesn't matter
```

If the length of authz ids for actors is different from the length of plaintext names in the list, then we return `bad_actor` (which is what we're seeing in the log). `convert_actor_names_to_ids` simply fetches the authz ids for all the clients and users that matches those names and combines them together, resulting in  (in the failure case) an authz id for both the user and the client. This will never work.

**Comment by cmoscardi** [comment] 2015-12-14 18:36
+1, just ran into this.

**Comment by marcparadise** [comment] 2016-08-26 17:22
Resolved with changes from: 
* #912
* #905 
* #917 

I'll close this issue once the last of those lands.

**Closed** 2016-09-22 17:39 UTC
