### ISSUE TITLE
chef-server-ctl upgrade fails when a cookbook has no name metadata

### ISSUE THREAD

**Issue by tas50** [chef/chef-server#250] opened 2015-05-12 19:12 UTC
I'm running into issues upgrading my Chef 11 server to Chef 12.  Apparently I have an unknown number of abandoned cookbooks in my repo that lack the name metadata attribute.  Running chef-server-ctl upgrade gets fairly far in and then bricks the server when it tries to upgrade:

ERROR: Chef::Exceptions::MetadataNotValid: Cookbook loaded at path(s) [/tmp/d20150511-10992-6s1wan/install_from] has invalid metadata: The `name' attribute is required in cookbook metadata
Failed uploading transformed data to the Chef 12 server

**Comment by mmzyk** [comment] 2015-05-12 20:51
@tas50 Yeah, this is an issue we're aware of, but haven't yet addressed or fixed in anyway. The original issue is here https://github.com/chef/chef-server/issues/118 so I'm going to close this as a duplicate.

However, your server isn't bricked. We worked very hard to try and make that not the case. Since it's a side by side install in the default case, you can use chef-server-ctl to shut down the Chef 12 server and then point to /opt/chef-server/chef-server-ctl and fire the Chef 11 server back up, as it still resides on the system with all of it's date and that is the chef-server-ctl that controls it. Installing the Chef server 12 package will make /opt/opscode/chef-server-ctl come first in the path, hence why the full path is needed.

Also, all of your data during the process is saved to folders in /tmp. So you can look for /tmp/chef11-<randomstring> and find your Chef 11 data, and look for /tmp/chef12-<randomstring> and find the Chef 12 data. This data is stored as json, so if need be you can modify the data in the /tmp/chef12-* directory and pick the upgrade back up using the individual ctl upgrade commands as doc'd here: https://docs.chef.io/upgrade_server_open_source_notes.html#manual-upgrades

The chef-server-ctl chef12-upgrade-upload takes an option to use the data on disk. Also, the upload process will pick up where it left off.

Feel free to ask any questions you have and we'll do our best to answer them. If you're on irc, I'm mmzyk and I'm happy to help out.

**Closed** 2015-05-12 20:51 UTC

**Comment by vinyar** [comment] 2015-09-13 19:36
oldie but a goodie. When upgrading take special care to note the version of chef-server. 11.0.x will have more issues than 11.1.x. 

Easiest way to mitigate the issue is to either upgrade 11.0 to 11.1 or to do a data backup from 11.0 and do a data restore to 11.1, then proceed with the upgrade as per docs above.
