### ISSUE TITLE
chef-server-ctl restore --cleanse chef_backup-xxx-xxxx-xxx.tar.gz fails at "private-chef::rabbitmq line 116"

### ISSUE THREAD

**Issue by swapnilpotnis** [chef/chef-server#1265] opened 2017-05-09 17:11 UTC
I have created the backup of chef server using
`chef-server ctl backup` command.

Trying to restore the chef-server from the generated "chef-backup-xxx-xxx.tar.gz" leads to the following error:

`[2017-05-09T15:58:37+00:00] INFO: runit_service[rabbitmq] enabled
[2017-05-09T15:58:37+00:00] INFO: Processing execute[/opt/opscode/bin/private-chef-ctl start rabbitmq] action run (private-chef::rabbitmq line 116)
[2017-05-09T15:58:42+00:00] INFO: Retrying execution of execute[/opt/opscode/bin/private-chef-ctl start rabbitmq], 19 attempt(s) left
[2017-05-09T15:58:49+00:00] INFO: Retrying execution of execute[/opt/opscode/bin/private-chef-ctl start rabbitmq], 18 attempt(s) left
[2017-05-09T15:58:56+00:00] INFO: Retrying execution of execute[/opt/opscode/bin/private-chef-ctl start rabbitmq], 17 attempt(s) left
[2017-05-09T15:59:03+00:00] INFO: Retrying execution of execute[/opt/opscode/bin/private-chef-ctl start rabbitmq], 16 attempt(s) left
Terminated
`

Can someone please provide me some solution?? Have been struggling with this issue for quite sometime now.

**Comment by irvingpop** [comment] 2017-05-09 23:53
Since we can assume the restore is happening on the same chef server version (which is what??) and topology (standalone?) -  can you check the rabbitmq error log to see why it is refusing to start?

**Comment by swapnilpotnis** [comment] 2017-05-10 12:33
RabbitMQ Logs not showing any sort of Errors.
Actually, I missed a vital piece of information I guess. 
The Chef-Server on which I am trying to perform a Restore lies in a Docker Container.

**Comment by irvingpop** [comment] 2017-05-10 16:08
ah, so this isn't about backup restores at all :)

All of our omnibus-packaged servers (including chef server) expect to interact with a functioning and detectable init system - that is almost never available in docker containers, which is why we can't support users today running our servers in containers.   Please reproduce on a VM or bare metal.

**Comment by marcparadise** [comment] 2017-05-10 16:27
While we don't support running in a container, I have been able to get it going by ensuring that the new chef server container is running some kind of supervisor, such as `supervisord`; or you could spawn the runit supervisor that ships with Chef Server in as a background task in your run script, before issuing `chef-server-ctl start`

**Comment by marcparadise** [comment] 2017-05-16 19:52
Closing this issue since this is in a container installation of Chef Server.  @swapnilpotnis I do hope that my suggestion above was of some help.

**Closed by marcparadise** 2017-05-16 19:52 UTC
