### ISSUE TITLE
Data bag search doesn't work correctly for encrypted arrays

### ISSUE THREAD

**Issue by adibsaad** [chef/chef-server#876] opened 2016-07-10 02:32 UTC
No output to give, just do `search(:data_bag_name, 'some_field:some_element')`, and if `some_field` is supposed to be an array of strings, one of which is `some_element`, and if the data bag is encrypted, it won't send back a result.

**Comment by stevendanna** [comment] 2016-12-05 23:30
Thank you for taking the time to file this issue.  My apologies no one responded before now.  I'm going to close this since this is expected behavior.  The chef-server does not have the keys for the encrypted item and can thus not see the plaintext of the item.  Without the plaintext we cannot index it for search.  I've opened a PR to update the documentation to make this more clear: https://github.com/chef/chef-web-docs/pull/300

**Closed by stevendanna** 2016-12-05 23:30 UTC
