### ISSUE TITLE
failed to migrate at level 28 due to nginx can't be stopped

### ISSUE THREAD

**Issue by congaframe** [chef/chef-server#825] opened 2016-04-28 14:44 UTC
Hi,
I'm trying to upgrade Chef Server from 12.2 to 12.5 but it failed at this step: 

```
[private-chef-upgrade] - Current Migration Version: 1.27
[private-chef-upgrade] - Starting Migration 1.28
[private-chef-upgrade] -    Stopping Services ["nginx", "opscode-erchef"]
[private-chef-upgrade] - Error: service nginx failed to stop, killing gracefully...
found stuck pids still running in process group: 825 979 980 981, sending SIGKILL
[private-chef-upgrade] - Failure: service nginx could not be stopped or killed.
```

(I search for those pids but they all already gone/been killed) 

I notice that running `chef-server-ctl stop` earlier doesn't give me any output. 
I followed the official guide here: https://docs.chef.io/upgrade_server.html
and currenlty at step 5: `chef-server-ctl upgrade`
I tried to manually kill the process: 
`root     12679 11368  0 15:34 ?        00:00:00 /opt/opscode/embedded/sbin/nginx -c /var/opt/opscode/nginx/etc/nginx.conf`
but it seems to be restarted itself. 

The migration level is: 

```
cat /var/opt/opscode/upgrades/migration-level
{"major":1,"minor":27}
```

I'm running Debian 7.9
Chef Server was 12.2 upgrading to 12.5 

Please let me know if you need any further information

**Comment by congaframe** [comment] 2016-04-28 15:51
In an attempt to manually fix this, I have remove `nginx` from the following file: 
`upgrades/001/028_server_admins_global_group.rb` and manullay `stop private-chef-runsvdir`, kill nginx. 
But it failed to stop `opscode-erchef` as well.
```
[private-chef-upgrade] - Current Migration Version: 1.27
[private-chef-upgrade] - Starting Migration 1.28
[private-chef-upgrade] - 	Stopping Services ["opscode-erchef"]
[private-chef-upgrade] - Error: service opscode-erchef failed to stop, killing gracefully...
found stuck pids still running in process group: 1092, sending SIGKILL
```

I also try to run `chef-server-ctl stop` manually but that doesn't seem to get any affect on those services. So may be there is something wrong with `chef-server-ctl` here ?

**Comment by congaframe** [comment] 2016-04-28 16:37
I cheated a little bit, removing `stop_services(["nginx","opscode-erchef"])` from `/opt/opscode/embedded/upgrades/001/028_server_admins_global_group.rb`, and it is now giving me new error : `Could not connect to mover service`

```
[private-chef-upgrade] - Current Migration Version: 1.27
[private-chef-upgrade] - Starting Migration 1.28
[private-chef-upgrade] - 	Starting Services ["oc_bifrost", "postgresql"]
[private-chef-upgrade] - Sleeping for 15 seconds while services comes online...
[private-chef-upgrade] - 	Restarting Service opscode-chef-mover
[private-chef-upgrade] - Sleeping for 15 seconds while service opscode-chef-mover comes back online...
[private-chef-upgrade] - Creating global group server-admins with read and create access on users container
[private-chef-upgrade] - 	Running Command: /opt/opscode/embedded/bin/escript /opt/opscode/embedded/service/opscode-chef-mover/scripts/migrate mover_server_admins_global_group_callback normal mover_transient_queue_batch_migrator with options {}

Could not connect to mover service

/opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:14:in `instance_eval': Partybus failed to execute command '/opt/opscode/embedded/bin/escript /opt/opscode/embedded/service/opscode-chef-mover/scripts/migrate mover_server_admins_global_group_callback normal mover_transient_queue_batch_migrator' exitstatus: 1 (RuntimeError)
	from /opt/opscode/embedded/service/partybus/lib/partybus/migration_api/v1.rb:97:in `run_command'
	from (eval):11:in `block in run'
	from /opt/opscode/embedded/service/partybus/lib/partybus/migration_api/v1.rb:14:in `instance_eval'
	from /opt/opscode/embedded/service/partybus/lib/partybus/migration_api/v1.rb:14:in `initialize'
	from /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:25:in `new'
	from /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:25:in `define_upgrade'
	from (eval):1:in `run'
	from /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:14:in `instance_eval'
	from /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:14:in `run'
	from /opt/opscode/embedded/service/partybus/lib/partybus/migrations.rb:41:in `run_migration'
	from ./bin/partybus:62:in `block in do_upgrade'
	from ./bin/partybus:58:in `each'
	from ./bin/partybus:58:in `do_upgrade'
	from ./bin/partybus:79:in `block in <main>'
	from ./bin/partybus:70:in `open'
	from ./bin/partybus:70:in `<main>'
```

**Comment by knyar** [comment] 2016-10-26 22:45
I believe the original problem is caused by a bug in `runit` cookbook: https://github.com/chef-cookbooks/runit/issues/207

**Comment by phene** [comment] 2017-03-06 23:37
I'm running into a similar issue at Migration 1.25

```
[private-chef-upgrade] - Starting Migration 1.25
[private-chef-upgrade] - 	Stopping Services ["nginx", "opscode-erchef"]
ok: down: nginx: 90s, normally up
down: nginx: 94s, normally up; run: log: (pid 11417) 1372s
[private-chef-upgrade] - Error: service nginx failed to stop, killing gracefully...
could not find nginx runit pidfile (service already stopped?), cannot attempt SIGKILL...
ok: down: nginx: 97s, normally up
down: nginx: 100s, normally up; run: log: (pid 11417) 1378s
[private-chef-upgrade] - Failure: service nginx could not be stopped or killed.
```

**Comment by phene** [comment] 2017-03-07 01:34
After patching the chef-server's version of runit with:

```diff
status)
-      $RUNIT status $NAME && exit 0 || exit $?
+     $RUNIT status $NAME | grep "^run: $NAME" && exit 0 || exit 1
```

I got a similar error as above:

```
[private-chef-upgrade] - Creating global group server-admins with read and create access on users container
[private-chef-upgrade] - 	Running Command: /opt/opscode/embedded/bin/escript /opt/opscode/embedded/service/opscode-chef-mover/scripts/migrate mover_server_admins_global_group_callback normal mover_transient_queue_batch_migrator with options {}
Unknown error error
 Unknown reason function_clause

=ERROR REPORT==== 7-Mar-2017::01:29:00 ===
{error,function_clause}

An unknown error has occurred.

bundler: failed to load command: ./bin/partybus (./bin/partybus)
RuntimeError: Partybus failed to execute command '/opt/opscode/embedded/bin/escript /opt/opscode/embedded/service/opscode-chef-mover/scripts/migrate mover_server_admins_global_group_callback normal mover_transient_queue_batch_migrator' exitstatus: 1
  /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:14:in `instance_eval'
  /opt/opscode/embedded/service/partybus/lib/partybus/migration_api/v1.rb:97:in `run_command'
  (eval):11:in `block in run'
  /opt/opscode/embedded/service/partybus/lib/partybus/migration_api/v1.rb:14:in `instance_eval'
  /opt/opscode/embedded/service/partybus/lib/partybus/migration_api/v1.rb:14:in `initialize'
  /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:25:in `new'
  /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:25:in `define_upgrade'
  (eval):1:in `run'
  /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:14:in `instance_eval'
  /opt/opscode/embedded/service/partybus/lib/partybus/dsl_runner.rb:14:in `run'
  /opt/opscode/embedded/service/partybus/lib/partybus/migrations.rb:41:in `run_migration'
  /opt/opscode/embedded/service/partybus/bin/partybus:62:in `block in do_upgrade'
  /opt/opscode/embedded/service/partybus/bin/partybus:58:in `each'
  /opt/opscode/embedded/service/partybus/bin/partybus:58:in `do_upgrade'
  /opt/opscode/embedded/service/partybus/bin/partybus:79:in `block in <top (required)>'
  /opt/opscode/embedded/service/partybus/bin/partybus:70:in `open'
  /opt/opscode/embedded/service/partybus/bin/partybus:70:in `<top (required)>'
```

**Comment by phene** [comment] 2017-03-07 20:06
Filed new issue: https://github.com/chef/chef-server/issues/1124

**Comment by phene** [comment] 2017-03-07 23:22
@congaframe Try [this](https://github.com/chef/chef-server/issues/1124#issuecomment-284891779)

**Comment by PrajaktaPurohit** [comment] 2019-12-18 21:58
@congaframe Thank you for reporting this issue. At this time, it looks like fixing #1124 should fix this issue as well. Closing in favor of that. Please feel free to reopen if it appears to be separate issue.

**Closed by PrajaktaPurohit** 2019-12-18 21:58 UTC
Labels: Status: Untriaged
