### ISSUE TITLE
Chef Manage install fails with use of apt.conf.d proxy

### ISSUE THREAD

**Issue by rgormley** [chef/chef-server#52] opened 2015-01-02 20:50 UTC
Brand new Ubuntu Server 14.04.1 install - in apt.conf.d, I connected to a local apt-cacher-ng instance:

`Acquire::http { Proxy "http://a.b.c.d:3142"; };`

results in install of Chef Manage (via `chef-server-ctl install opscode-manage` errors out:

```
TDERR: W: Failed to fetch https://packagecloud.io/chef/stable/ubuntu/dists/lucid/main/source/Sources  Proxy CONNECT aborted

W: Failed to fetch https://packagecloud.io/chef/stable/ubuntu/dists/lucid/main/binary-amd64/Packages  Proxy CONNECT aborted

W: Failed to fetch https://packagecloud.io/chef/stable/ubuntu/dists/lucid/main/binary-i386/Packages  Proxy CONNECT aborted

E: Some index files failed to download. They have been ignored, or old ones used instead.
---- End output of apt-get update ----
Ran apt-get update returned 100
```

[truncated]

```
Recipe: private-chef::add_ons_remote
  * package[opscode-manage] action install
    * No version specified, and no candidate version available for opscode-manage
================================================================================
Error executing action `install` on resource 'package[opscode-manage]'
================================================================================


Chef::Exceptions::Package
-------------------------
No version specified, and no candidate version available for opscode-manage


Resource Declaration:
---------------------
# In /opt/opscode/embedded/cookbooks/private-chef/recipes/add_ons_remote.rb

 48:   package pkg do
 49:     notifies :create, "ruby_block[addon_install_notification_#{pkg}]", :immediate
 50:   end
#Acquire::http { Proxy "http://a.b.c.d:3142"; };
 51: end



Compiled Resource:
------------------
# Declared in /opt/opscode/embedded/cookbooks/private-chef/recipes/add_ons_remote.rb:48:in `block in from_file'

package("opscode-manage") do
  action :install
  retries 0
  retry_delay 2
  guard_interpreter :default
  package_name "opscode-manage"
  cookbook_name :"private-chef"
  recipe_name "add_ons_remote"
end




Running handlers:
  - #<Class:0x000000040e58b8>::AddonInstallHandler
Running handlers complete

[2015-01-02T12:40:52-08:00] FATAL: Stacktrace dumped to /opt/opscode/embedded/cookbooks/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 17.097952201 seconds
[2015-01-02T12:40:52-08:00] FATAL: Chef::Exceptions::Package: package[opscode-manage] (private-chef::add_ons_remote line 48) had an error: Chef::Exceptions::Package: No version specified, and no candidate version available for opscode-manage
```

Disabling apt-cacher-ng (or rather the Proxy directive) allows the install to succeed. It should be noted that this doesn't appear to be an issue with apt-cacher-ng itself, as it is happily handling Ubuntu updates.

**Comment by stevendanna** [comment] 2015-01-13 14:33
I've confirmed what the original reporter is seeing outside of the chef-server-ctl recconfigure command by:

1. Installing apt-cacher-ng
2. Configuring apt to use a proxy on local host
3. Configuring the packagecloud.io source for apt
4. Running `apt-get update`

My hunch is that the problem is that the packagecloud.io sources use HTTPS and either (1) that isn't supported by apt-cacher-ng or (2) it is supported but needs some special configuration.  Can you confirm that all of your other sources are HTTP rather than https?

I made a few attempts to find a config of apt-cacher-ng that works nicely with HTTPs but haven't had any luck yet.

**Comment by rgormley** [comment] 2015-01-13 19:46
Confirmed. The upstream is http, not https - the standard sources.list as supplied with Ubuntu 12/14.

**Comment by stevendanna** [comment] 2016-11-02 01:16
I'm going to close this one out.  The add-ons installer no longer configures apt repositories and rather downloads the installers directly from our package service.

**Closed by stevendanna** 2016-11-02 01:16 UTC
