### ISSUE TITLE
[chef-server-ctl reconfigure] error while installing chef server on ubuntu LTS 16.04.1

### ISSUE THREAD

**Issue by GeetP** [chef/chef-server#1008] opened 2016-11-10 12:22 UTC
Hi all,
I've installed Chef-server 12.10.1 on Ubuntu-16.04.1 VM
I run the command chef-server-ctl reconfigure and got ERROR
The error is as follows:
Recipe: private-chef::bootstrap
  * execute[/opt/opscode/bin/chef-server-ctl start postgresql] action run
    - execute /opt/opscode/bin/chef-server-ctl start postgresql
  * execute[/opt/opscode/bin/chef-server-ctl start oc_bifrost] action run
    - execute /opt/opscode/bin/chef-server-ctl start oc_bifrost
  * ruby_block[bootstrap-chef-server-data] action run
    
    ================================================================================
    Error executing action `run` on resource 'ruby_block[bootstrap-chef-server-data]'    ================================================================================
    
    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass
    
    Cookbook Trace:
    ---------------
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:97:in `create_superuser_in_erchef'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:50:in `block in bootstrap'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:55:in `block in with_service_connection'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:44:in `with_connection'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:52:in `with_service_connection'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:49:in `bootstrap'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/bootstrap.rb:35:in `block (2 levels) in from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/bootstrap.rb
    
     33: ruby_block "bootstrap-chef-server-data" do
     34:   block do
     35:     ChefServerDataBootstrap.new(node).bootstrap
     36:   end
     37:   not_if { OmnibusHelper.has_been_bootstrapped? }
     38:   notifies :restart, 'service[opscode-erchef]'
     39: end
     40: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/bootstrap.rb:33:in `from_file'
    
    ruby_block("bootstrap-chef-server-data") do
      action [:run]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      block_name "bootstrap-chef-server-data"
      declared_type :ruby_block
      cookbook_name "private-chef"
      recipe_name "bootstrap"
      block #<Proc:0x000000080fec60@/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/bootstrap.rb:34>
      not_if { #code block }
    end
    
    Platform:
    ---------
    x86_64-linux
    

Running handlers:
[2016-11-10T15:42:21+05:30] ERROR: Running exception handlers
Running handlers complete
[2016-11-10T15:42:21+05:30] ERROR: Exception handlers complete
Chef Client failed. 19 resources updated in 01 minutes 07 seconds
[2016-11-10T15:42:21+05:30] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2016-11-10T15:42:21+05:30] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-11-10T15:42:21+05:30] FATAL: NoMethodError: ruby_block[bootstrap-chef-server-data] (private-chef::bootstrap line 33) had an error: NoMethodError: undefined method `[]' for nil:NilClass

I Copied pivotal.pem from directory "/opt/opscode/embedded/service/omnibus-ctl/spec/fixtures".

and if I remove pivotal.pem from directory "/etc/opscode/" then it gives following error:

Recipe: private-chef::default
  * directory[/etc/opscode] action create (up to date)
  * directory[/etc/opscode/logrotate.d] action create (up to date)
[2016-11-10T16:33:03+05:30] FATAL: 

-----------------------------------------------------------------------
BOOT007: The secrets file (/etc/opscode/private-chef-secrets.json) is present
         but the file /etc/opscode/pivotal.pem is missing.

         Ensure that private-chef-secrets.json is copied into /etc/opscode from the
         first Chef Server node that you brought online, then run
         'chef-server-ctl reconfigure' again.
-----------------------------------------------------------------------
I have just started to learn chef tool. Can anybody help me out here?
Thanks

**Comment by stevendanna** [comment] 2016-11-10 13:12
@GeetP Since this is a brand new node, the easiest thing might be to run a `chef-server-ctl cleanse` (which will remove all the on-disk state) and try `chef-server-ctl reconfigure` again.  When you do that, if you could use `tee` to capture all of the output to a file as well: `chef-server-ctl reconfigure | tee reconfigure.log` that way if it fails we can take a look at the entire log.

**Comment by GeetP** [comment] 2016-11-10 16:10
it worked... Thanks alot @stevendanna

**Comment by stevendanna** [comment] 2016-11-12 12:46
@GeetP I'm glad that worked.  I'm going to close this bug as a duplicate of https://github.com/chef/chef-server/issues/987 which I believe is the same issue.  Thank you for taking the time to report it and apologies for any trouble this has caused you.

**Closed by stevendanna** 2016-11-12 12:46 UTC

**Comment by mateuslima90** [comment] 2017-01-30 00:45
stevendanna,

Thanks your tip worked chef.

**Comment by d4rk8l1tz** [comment] 2017-07-31 09:11
@stevendanna  this helped me today. Thank you !
