### ISSUE TITLE
Chef 12 Pedant Failure On First Run

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#34] opened 2014-11-25 22:12 UTC
Saw these errors occur on the first run of a looping `chef-server-ctl test` run.
This system had at least one existing org and other objects present.

So far, 29 additional runs have succeeded.

    Failures:

      1) Data Bag API endpoint with data bags that have items a request to /data/<bag> GET shows a full data bag
	 ESC[31mFailure/Error:ESC[0m ESC[31mget(named_data_bag_url, requestor).should look_like fetch_full_data_bag_success_responseESC[0m
	   ESC[31mResponse should have HTTP status code 200 ('OK'), but it was actually 404 ('Not Found')ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-expectations-2.14.5/lib/rspec/expectations/fail_with.rb:32:in `fail_with'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-expectations-2.14.5/lib/rspec/expectations/handler.rb:36:in `handle_matcher'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-expectations-2.14.5/lib/rspec/expectations/syntax.rb:53:in `should'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/bundler/gems/chef-pedant-dad401df0955/spec/api/data_bag/complete_endpoint_spec.rb:358:in `block (6 levels) in <top (required)>'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:114:in `instance_eval'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:114:in `block in run'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:254:in `with_around_each_hooks'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example.rb:111:in `run'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:390:in `block in run_examples'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:386:in `map'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:386:in `run_examples'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:371:in `run'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `block in run'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `map'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `run'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `block in run'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `map'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `run'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `block in run'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `map'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `run'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `block in run'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `map'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/example_group.rb:372:in `run'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:28:in `map'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:28:in `block in run'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/reporter.rb:58:in `report'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:25:in `run'ESC[0m
    ESC[36m     # /opt/opscode/embedded/service/gem/ruby/1.9.1/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:80:in `run'ESC[0m
    ESC[36m     # ./bin/oc-chef-pedant:16:in `<main>'ESC[0m

      2) ACL API /<type>/<name>/_acl endpoint for data type /data/<name>/_acl/update endpoint PUT /data/<name>/_acl/update normal user with all permissions except GRANT returns 403
	 ESC[31mFailure/Error:ESC[0m ESC[31mpost(creation_url, setup_user,ESC[0m
	   ESC[31mResponse should have HTTP status code 201 ('Created'), but it was actually 403 ('Forbidden')ESC[0m
    ESC[36m     # ./spec/api/account/account_acl_spec.rb:887:in `block (5 levels) in <top (required)>'ESC[0m

      3) opscode-account user association user not in org can be invited to the org by an admin when the inviting admin is removed from admins group, invites issued by that admin cannot be accepted
	 ESC[31mFailure/Error:ESC[0m ESC[31mlet(:test_user) { platform.create_user(test_username) }ESC[0m
	 ESC[31mRuntimeErrorESC[0m:
	   ESC[31mUnknown key type. Must be String or OpenSSL::PKey::RSA. nilESC[0m
    ESC[36m     # ./lib/pedant/multitenant/platform.rb:106:in `new'ESC[0m
    ESC[36m     # ./lib/pedant/multitenant/platform.rb:106:in `create_user'ESC[0m
    ESC[36m     # ./spec/api/account/account_association_spec.rb:612:in `block (5 levels) in <top (required)>'ESC[0m
    ESC[36m     # ./spec/api/account/account_association_spec.rb:625:in `block (5 levels) in <top (required)>'ESC[0m

    Finished in 2 minutes 28.3 seconds
    ESC[31m130 examples, 3 failures, 2 pendingESC[0m

**Comment by sdelano** [comment] 2015-05-13 18:44
@sean-horn has acknowledged that if he can't reproduce this on Chef Server 12.0.8 by tomorrow then we can close this ticket.

**Comment by stevendanna** [comment] 2015-06-08 10:11
@sdelano @sean-horn I'm going to close this ticket out.  I don't doubt that there are conditions under which our pedant tests may fail on the first run; however, we haven't been seeing any errors in CI (where theses tests are run on nearly every commit) and don't have a reproduction on a non-RC version.

Thanks for taking the time to report this @sean-horn.  If you do see further pedant failures, please report them and we will look into them.

**Closed by stevendanna** 2015-06-08 10:11 UTC
