### ISSUE TITLE
gmake omnibus failed during build chef-server

### ISSUE THREAD

**Issue by ylvmw** [chef/chef-server#636] opened 2015-11-20 13:57 UTC
I tried building chef-server On CentOS 6.4, but got the error during the process:

```

               [Builder: bookshelf] I | $ gmake omnibus
               [Builder: bookshelf] I | Execute: `gmake omnibus': 266.4376s
               [Builder: bookshelf] I | Build bookshelf: 266.4381s
The following shell command exited with status 2:

    $ CFLAGS=-I/opt/opscode/embedded/include CPPFLAGS=-I/opt/opscode/embedded/include CXXFLAGS=-I/opt/opscode/embedded/include LDFLAGS=-Wl,-rpath,/opt/opscode/embedded/lib -L/opt/opscode/embedded/lib LD_RUN_PATH=/opt/opscode/embedded/lib MAKE=gmake PATH=/opt/opscode/bin:/opt/opscode/embedded/bin:/usr/local/lib/ruby/gems/2.2.0/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin PKG_CONFIG_PATH=/opt/opscode/embedded/lib/pkgconfig REL_VERSION=12.2.0+20151120133532 gmake omnibus

Output:

    rm -rf _build
/var/cache/omnibus/src/bookshelf/rebar3 update
```

Could some one give some hints on this? Thanks a lot!

**Comment by stevendanna** [comment] 2015-11-20 14:10
Is there any more output from this failure?  You can increase the debugging level by doing:

  bundle exec omnibus build chef-server -l internal

which will print a lot more information and might provide more useful output.

**Comment by ylvmw** [comment] 2015-11-20 14:19
Yeah, please the see the detailed log below:
```
              [Builder: bookshelf] W | [3/3] Failed to execute command. Retrying in 40 seconds...
               [Builder: bookshelf] I | Environment:
               [Builder: bookshelf] I |   CFLAGS="-I/opt/opscode/embedded/include"
               [Builder: bookshelf] I |   CPPFLAGS="-I/opt/opscode/embedded/include"
               [Builder: bookshelf] I |   CXXFLAGS="-I/opt/opscode/embedded/include"
               [Builder: bookshelf] I |   LDFLAGS="-Wl,-rpath,/opt/opscode/embedded/lib -L/opt/opscode/embedded/lib"
               [Builder: bookshelf] I |   LD_RUN_PATH="/opt/opscode/embedded/lib"
               [Builder: bookshelf] I |   MAKE="gmake"
               [Builder: bookshelf] I |   PATH="/opt/opscode/bin:/opt/opscode/embedded/bin:/usr/local/lib/ruby/gems/2.2.0/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"
               [Builder: bookshelf] I |   PKG_CONFIG_PATH="/opt/opscode/embedded/lib/pkgconfig"
               [Builder: bookshelf] I |   REL_VERSION="12.2.0+20151120141140"
               [Builder: bookshelf] I | $ gmake omnibus
                                    D | rm -rf _build
                                    D | /var/cache/omnibus/src/bookshelf/rebar3 update
                                    D | ===> Updating package registry...
                                    D | ===> Writing registry to /root/.cache/rebar3/hex/default/registry
                                    D | ===> Generating package index...
                                    D | ===> Writing index to /root/.cache/rebar3/hex/default/packages.idx
                                    D | /var/cache/omnibus/src/bookshelf/rebar3 do compile, release
                                    D | ===> Verifying dependencies...
                                    D | ===> Fetching eper ({git,"git://github.com/massemanet/eper.git",
                                    D |                                 {ref,"80e7cd6446d26d2423f2acd37253826bb3152964"}})
                                    D | ===> Fetching erlsom ({git,"git://github.com/opscode/erlsom.git",
                                    D |                                  {ref,
                                    D |                                      "c5ca9fca1257f563d78b048e35ac60832ec80584"}})
                                    D | ===> Fetching erlware_commons ({git,
                                    D |                                        "git://github.com/erlware/erlware_commons.git",
                                    D |                                        {ref,
                                    D |                                         "03f76c6ef2e854a11a62c3a1992f047ab0a0a69e"}})
                                    D | ===> Plugin rebar_vsn_plugin not available. It will not be used.
                                    D | ===> Fetching exec ({git,"https://github.com/saleyn/erlexec.git",
                                    D |                                 {ref,"b3548d6973a1529bfada3cab9bbf602d43fb5e46"}})
                                    D | ===> Fetching pc ({pkg,<<"pc">>,<<"1.1.0">>})
                                    D | ===> Compiling pc
                                    D | ===> Fetching iso8601 ({git,
                                    D |                                   "git://github.com/opscode/erlang_iso8601.git",
                                    D |                                   {ref,
                                    D |                                       "25675e1df8b2bade1fb539cd9a913d61b90468dd"}})
                                    D | ===> Fetching lager ({git,"git://github.com/basho/lager",
                                    D |                                  {ref,"d33ccf3b69de09a628fe38b4d7981bb8671b8a4f"}})
                                    D | ===> Fetching meck ({git,"https://github.com/eproxus/meck.git",
                                    D |                                 {ref,"17b0ea5b7d9c93af3a52b5152c6bee14302b3885"}})
                                    D | ===> Fetching mini_s3 ({git,"git://github.com/opscode/mini_s3.git",
                                    D |                                   {ref,
                                    D |                                       "1cf296868077caefa6791f4996145a369c49091b"}})
                                    D | ===> Fetching mixer ({git,"git://github.com/opscode/mixer.git",
                                    D |                                  {ref,"58ded93d5c47675899d8e5e1589270f340ea66c5"}})
                                    D | ===> Fetching opscoderl_wm ({git,
                                    D |                                     "git://github.com/opscode/opscoderl_wm.git",
                                    D |                                     {ref,
                                    D |                                      "64db62e070da58cf7bb0caebde7a3f11c2e3cbbb"}})
                                    D | ===> Fetching sync ({git,"https://github.com/rustyio/sync.git",
                                    D |                                 {ref,"ae7dbd4e6e2c08d77d96fc4c2bc2b6a3b266492b"}})
                                    D | ===> Fetching envy ({git,"git://github.com/manderson26/envy.git",
                                    D |                                 {ref,"e6ba39664a1016ed309ea44269247943de2eb16b"}})
                                    D | ===> Fetching goldrush ({git,"git://github.com/DeadZen/goldrush.git",
                                    D |                                    {ref,
                                    D |                                        "71e63212f12c25827e0c1b4198d37d5d018a7fec"}})
                                    D | ===> Fetching ibrowse ({git,"git://github.com/opscode/ibrowse",
                                    D |                                   {ref,
                                    D |                                       "8f3f6a3a30730b193cc340a8885a960586dc98de"}})
                                    D | ===> Fetching rebar_vsn_plugin ({git,
                                    D |                                         "https://github.com/erlware/rebar_vsn_plugin.git",
                                    D |                                         {ref,
                                    D |                                          "fd40c960c7912193631d948fe962e1162a8d1334"}})
                                    D | ===> Fetching webmachine ({git,"git://github.com/basho/webmachine",
                                    D |                                   {ref,
                                    D |                                    "7677c240f4a7ed020f4bab48278224966bb42311"}})
                                    D | ===> Fetching mochiweb ({git,"git://github.com/basho/mochiweb.git",
                                    D |                                    {ref,
                                    D |                                        "ade2a9b29a11034eb550c1d79b4f991bf5ca05ba"}})
                                    D | ===> Compiling rebar_vsn_plugin
                                    D | ===> Compiling iso8601
                                    D | ===> Compiling eper
                                    D | ===> Compiling ibrowse
                                    D | /var/cache/omnibus/src/bookshelf/_build/default/lib/ibrowse/src/ibrowse.erl:627: Warning: wrong number of arguments in format call
                                    D |
                                    D | ===> Compiling envy
                                    D | ===> Compiling mini_s3
                                    D | ===> Compiling mochiweb
                                    D | ===> Compiling webmachine
                                    D | ===> Compiling opscoderl_wm
                                    D | ===> Compiling sync
                                    D | ===> Compiling mixer
                                    D | ===> Compiling meck
                                    D | ===> Compiling goldrush
                                    D | ===> Compiling lager
                                    D | ===> Compiling exec
                                    D | ===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace
                                    D | ===> When submitting a bug report, please include the output of `rebar3 report "your command"`
                                    D | gmake: *** [omnibus] Error 1
               [Builder: bookshelf] I | Execute: `gmake omnibus': 250.5295s
               [Builder: bookshelf] I | Build bookshelf: 250.5301s
The following shell command exited with status 2:

    $ CFLAGS=-I/opt/opscode/embedded/include CPPFLAGS=-I/opt/opscode/embedded/include CXXFLAGS=-I/opt/opscode/embedded/include LDFLAGS=-Wl,-rpath,/opt/opscode/embedded/lib -L/opt/opscode/embedded/lib LD_RUN_PATH=/opt/opscode/embedded/lib MAKE=gmake PATH=/opt/opscode/bin:/opt/opscode/embedded/bin:/usr/local/lib/ruby/gems/2.2.0/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin PKG_CONFIG_PATH=/opt/opscode/embedded/lib/pkgconfig REL_VERSION=12.2.0+20151120141140 gmake omnibus

Output:

    rm -rf _build
/var/cache/omnibus/src/bookshelf/rebar3 update
===> Updating package registry...
===> Writing registry to /root/.cache/rebar3/hex/default/registry
===> Generating package index...
===> Writing index to /root/.cache/rebar3/hex/default/packages.idx
/var/cache/omnibus/src/bookshelf/rebar3 do compile, release
===> Verifying dependencies...
===> Fetching eper ({git,"git://github.com/massemanet/eper.git",
                                {ref,"80e7cd6446d26d2423f2acd37253826bb3152964"}})
===> Fetching erlsom ({git,"git://github.com/opscode/erlsom.git",
                                 {ref,
                                     "c5ca9fca1257f563d78b048e35ac60832ec80584"}})
===> Fetching erlware_commons ({git,
                                       "git://github.com/erlware/erlware_commons.git",
                                       {ref,
                                        "03f76c6ef2e854a11a62c3a1992f047ab0a0a69e"}})
===> Plugin rebar_vsn_plugin not available. It will not be used.
===> Fetching exec ({git,"https://github.com/saleyn/erlexec.git",
                                {ref,"b3548d6973a1529bfada3cab9bbf602d43fb5e46"}})
===> Fetching pc ({pkg,<<"pc">>,<<"1.1.0">>})
===> Compiling pc
===> Fetching iso8601 ({git,
                                  "git://github.com/opscode/erlang_iso8601.git",
                                  {ref,
                                      "25675e1df8b2bade1fb539cd9a913d61b90468dd"}})
===> Fetching lager ({git,"git://github.com/basho/lager",
                                 {ref,"d33ccf3b69de09a628fe38b4d7981bb8671b8a4f"}})
===> Fetching meck ({git,"https://github.com/eproxus/meck.git",
                                {ref,"17b0ea5b7d9c93af3a52b5152c6bee14302b3885"}})
===> Fetching mini_s3 ({git,"git://github.com/opscode/mini_s3.git",
                                  {ref,
                                      "1cf296868077caefa6791f4996145a369c49091b"}})
===> Fetching mixer ({git,"git://github.com/opscode/mixer.git",
                                 {ref,"58ded93d5c47675899d8e5e1589270f340ea66c5"}})
===> Fetching opscoderl_wm ({git,
                                    "git://github.com/opscode/opscoderl_wm.git",
                                    {ref,
                                     "64db62e070da58cf7bb0caebde7a3f11c2e3cbbb"}})
===> Fetching sync ({git,"https://github.com/rustyio/sync.git",
                                {ref,"ae7dbd4e6e2c08d77d96fc4c2bc2b6a3b266492b"}})
===> Fetching envy ({git,"git://github.com/manderson26/envy.git",
                                {ref,"e6ba39664a1016ed309ea44269247943de2eb16b"}})
===> Fetching goldrush ({git,"git://github.com/DeadZen/goldrush.git",
                                   {ref,
                                       "71e63212f12c25827e0c1b4198d37d5d018a7fec"}})
===> Fetching ibrowse ({git,"git://github.com/opscode/ibrowse",
                                  {ref,
                                      "8f3f6a3a30730b193cc340a8885a960586dc98de"}})
===> Fetching rebar_vsn_plugin ({git,
                                        "https://github.com/erlware/rebar_vsn_plugin.git",
                                        {ref,
                                         "fd40c960c7912193631d948fe962e1162a8d1334"}})
===> Fetching webmachine ({git,"git://github.com/basho/webmachine",
                                  {ref,
                                   "7677c240f4a7ed020f4bab48278224966bb42311"}})
===> Fetching mochiweb ({git,"git://github.com/basho/mochiweb.git",
                                   {ref,
                                       "ade2a9b29a11034eb550c1d79b4f991bf5ca05ba"}})
===> Compiling rebar_vsn_plugin
===> Compiling iso8601
===> Compiling eper
===> Compiling ibrowse
/var/cache/omnibus/src/bookshelf/_build/default/lib/ibrowse/src/ibrowse.erl:627: Warning: wrong number of arguments in format call

===> Compiling envy
===> Compiling mini_s3
===> Compiling mochiweb
===> Compiling webmachine
===> Compiling opscoderl_wm
===> Compiling sync
===> Compiling mixer
===> Compiling meck
===> Compiling goldrush
===> Compiling lager
===> Compiling exec
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace
===> When submitting a bug report, please include the output of `rebar3 report "your command"`


Error:

    gmake: *** [omnibus] Error 1


/usr/local/lib/ruby/gems/2.2.0/bundler/gems/omnibus-9b2fe7d672da/lib/omnibus/util.rb:101:in `rescue in shellout!'


```

**Comment by stevendanna** [comment] 2015-11-20 14:23
Thanks, I'm gonna try to reproduce this.  It looks like a rebar compatibility issue.  Are you building from master or from a tag?

**Comment by ylvmw** [comment] 2015-11-20 14:25
I'm building from 12.2.0. Thanks!

**Comment by sdelano** [comment] 2015-11-20 17:20
@ylvmw - Unfortunately, some of the dependencies for certain projects that are bundled with the Chef Server are unlocked and can cause build failures if built in the future. This issue has been addressed on the master branch of chef-server via #629, which may or may not merge cleanly into 12.2.0.

**Comment by ylvmw** [comment] 2015-11-21 11:12
@sdelano - Could you let me know how to work around this in 12.2.0?

**Comment by stevendanna** [comment] 2017-02-22 00:20
@ylvmw Apologies there was no follow-up here. I'm going to close this out as the exec module has since been removed from the server.  If you are still looking for help building older versions, please reach out and we can see if we can help.

**Closed by stevendanna** 2017-02-22 00:20 UTC
