### ISSUE TITLE
Wrong error message `chef-server-ctl user-create`

### ISSUE THREAD

**Issue by im7mortal** [chef/chef-server#845] opened 2016-05-29 21:10 UTC
When I create user with a duplicate email Chef notice me that
`Response: User 'username' already exists`
### The version of the Chef Server you are running

Chef version is 12.6.0
chef-server-core_12.6.0-1_amd64.deb
### The operating system you are running it on

Ubuntu 14.04 64.  AWS EC2
### What you are trying to achieve but can't

I have `admin` with `user@example.com`
I tried to create `user` with the same email `user@example.com`
I had `Response: User 'user' already exists` 
### The steps to reproduce the issue you are seeing

Try to create new user with duplicate email.  
`sudo chef-server-ctl user-create -h`
### What you expect to see given the steps you've described

I expected to get message like `you can't use duplicate email`
### What you actually see given the steps you've described

 `Response: User 'user' already exists`

**Comment by stevendanna** [comment] 2016-11-02 01:08
Thanks for taking the time to report this.  I'm closing this as a duplicate of https://github.com/chef/chef-server/issues/59

**Closed by stevendanna** 2016-11-02 01:08 UTC
